services:
  api:
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      - DB_HOST=database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - domino_network

  database:
    image: postgres:16.2
    volumes:
      - ./domino_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - domino_network

networks:
  domino_network:
    driver: bridge
